version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rocas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  web:
    build: ./app
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 8003:80  # Cambia el puerto de escucha a 8080 en la máquina local
    depends_on:
      - web


volumes:
  postgres_data: